server:
  port: 8081

spring:
  application:
    name: mcp-client-demo
  ai:
#    openai:
#      api-key: ${DASHSCOPE_API_KEY}
#      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
#      model: qwen-max

    mcp:
      client:
        enabled: true
        name: spring-ai-mcp-client
        version: 1.0.0
        type: async
        request-timeout: 20s
        sse:
          connections:
            server:
              url: http://localhost:8080
              sse-endpoint: /sse
    dashscope:
      api-key: ${DASHSCOPE_API_KEY}
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      image:
        enabled: false
      chat:
        options:
          model: qwen-max