server:
  port: 9995
spring:
  application:
    name: spring-lifecycle
  datasource:
    url: jdbc:mysql://localhost:3306/db?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&autoReconnect=true&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: mysql
    username: root
    password: root
mybatis:
  mapper-locations: classpath:mappers/*.xml
context:
  initializer:
    classes: com.johar.test.springlifecycle.config.CustomApplicationInit

